module.exports = {
    name: 'help',
    description: 'Mostra la guida principale del bot',
    async execute(msg) {
        const text = [
            '🤖 GIOVABOT HELP',
            '',
            '💰 Economia',
            '• .saldo',
            '• .saldo top',
            '• .daily',
            '• .regala @utente importo',
            '• .banca',
            '• .scommessa @utente importo',
            '',
            '🎮 Giochi',
            '• .giochi',
            '• .slot',
            '• .dado [numero]',
            '• .blackjack',
            '• .roulette',
            '• .cavalli',
            '• .duello',
            '• .torneo',
            '• .battaglia',
            '• .trivia',
            '• .scelta',
            '',
            '🎣 Pesca',
            '• .pesca',
            '• .pesca help',
            '• .pesca meteo',
            '• .pesca boss',
            '• .pesca craft',
            '',
            '🏆 Progressione',
            '• .missioni',
            '• .achievements',
            '• .streaks',
            '• .stats',
            '• .classifica [gioco]',
            '',
            '📚 Scuola e utilità',
            '• .ripasso [argomento]',
            '• .novita',
            '• .meteo',
            '• .orario',
            '• .verifiche',
            '• .compiti',
            '• .voti',
            '• .sondaggio',
            '• .qr',
            '',
            '🧠 AI',
            '• .ai [richiesta]',
            '',
            '💡 Per una demo scolastica forte prova: .ripasso, .trivia, .verifiche, .compiti e .missioni'
        ].join('\n');

        await msg.reply(text);
    }
};
