module.exports = {
    name: 'help',
    description: 'Mostra la guida principale del bot',
    async execute(msg) {
        const text = [
            'GIOVABOT HELP',
            '',
            'Economia',
            '• .saldo',
            '• .saldo top',
            '• .daily',
            '• .regala @utente importo',
            '• .banca',
            '• .scommessa @utente importo',
            '',
            'Giochi',
            '• .giochi',
            '• .slot',
            '• .dado [numero]',
            '• .blackjack',
            '• .roulette',
            '• .cavalli',
            '• .duello',
            '• .torneo',
            '• .battaglia',
            '',
            'Pesca',
            '• .pesca',
            '• .pesca help',
            '• .pesca meteo',
            '• .pesca boss',
            '• .pesca craft',
            '',
            'Progressione',
            '• .missioni',
            '• .achievements',
            '• .streaks',
            '• .stats',
            '• .classifica [gioco]',
            '',
            'Utilita',
            '• .novita',
            '• .meteo',
            '• .orario',
            '• .verifiche',
            '• .compiti',
            '• .voti',
            '• .sondaggio',
            '• .qr',
            '',
            'AI',
            '• .ai [richiesta]',
            '',
            'Suggerimento: usa .giochi per la lista rapida dei giochi e .pesca help per il mega update pesca.'
        ].join('\n');

        await msg.reply(text);
    }
};
